# Generated by Django 3.2.4 on 2021-07-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total_tasks', models.IntegerField()),
                ('mistakes', models.IntegerField()),
                ('examples_of_mistakes', models.TextField()),
            ],
        ),
    ]
