# Generated by Django 3.2.4 on 2021-08-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.BooleanField()),
                ('numbers_of_tasks', models.IntegerField()),
                ('total', models.IntegerField()),
                ('number_example', models.IntegerField()),
                ('mistakes', models.IntegerField()),
                ('tasks', models.JSONField(default=[])),
                ('total_for_save', models.IntegerField()),
                ('mistakes_for_save', models.IntegerField()),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('result', models.IntegerField()),
                ('session', models.IntegerField()),
                ('action', models.CharField(max_length=10)),
            ],
        ),
    ]
