# Generated by Django 3.2.4 on 2021-08-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0002_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='numbers_of_tasks',
            new_name='number_of_tasks',
        ),
    ]
