# Generated by Django 3.2.4 on 2021-08-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0003_rename_numbers_of_tasks_game_number_of_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_example',
            field=models.IntegerField(default=0),
        ),
    ]
