# Generated by Django 3.2.4 on 2021-08-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0005_auto_20210802_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='a',
        ),
        migrations.RemoveField(
            model_name='game',
            name='b',
        ),
        migrations.RemoveField(
            model_name='game',
            name='result',
        ),
    ]
