# Generated by Django 3.2.4 on 2021-08-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0007_result_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mistakes_examples',
            field=models.JSONField(default=[]),
        ),
    ]
