# Generated by Django 3.2.4 on 2021-08-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0008_game_mistakes_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='number_of_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='number_example',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='permission',
            field=models.BooleanField(default=True),
        ),
    ]
